### ISSUE TITLE
اصلاح حرف «مـ ـمـ»

### ISSUE THREAD

**Issue by ahmaduxui** [aminabedi68/Mikhak#11]
حرف (م) تو نسخه ۳.۱ فونت میخک مشکل داره

![20220328_235025.jpg](https://user-images.githubusercontent.com/44550501/160471161-ddefd591-4de7-4e37-856f-5187b643bfa5.jpg)

![20220328_235650.jpg](https://user-images.githubusercontent.com/44550501/160472003-08c2df8e-7aa3-433c-88a1-3e500622cf39.jpg)

**Comment by aminabedi68** [comment]
مشکلی وجود ندارد، طراحی خود میم به این شکل است.
