### ISSUE TITLE
اندازه سه‌نقطه و دونقطه‌ها

### ISSUE THREAD

**Issue by AbbasAlimi** [aminabedi68/Mikhak#3]
سلام
تشکر بابت تهیه این فونت خوب
به نظر من شکل سه‌نقطه و دونقطه کوچک هستند و در نمایش کوچک فونت ، سه‌نقطه و دونقطه به شکل یک نقطه دیده می شوند .

**Comment by aminabedi68** [comment]
سلام و ممنون، میتونم خواهش کنم تصویر بفرستین، من دقیقا متوجه مشکل نشدم

**Comment by aminabedi68** [comment]
نسخۀ سوم رو چک کنین، امیدوارم بهتر شده باشه.
