### ISSUE TITLE
Tagging and Versioning Problem

### ISSUE THREAD

**Issue by molaeiali** [aminabedi68/Mikhak#4]
I wasn't gonna open another issue as I said here on [Estedad](https://github.com/aminabedi68/Estedad/issues/12) issues, but here there is another problem, why release tag is [2.2](https://github.com/aminabedi68/Mikhak/releases/tag/v2.2(2)) but the zip file is [2.2.2.zip](https://github.com/aminabedi68/Mikhak/releases/download/v2.2(2)/Mikhak-v2.2.2.zip)?

**Comment by aminabedi68** [comment]
going to check, thank you 👍

**Comment by aminabedi68** [comment]
fixed.
