### ISSUE TITLE
اضافه کردن نسخه‌ای با نقاط حروف جدا

### ISSUE THREAD

**Issue by mojtaba82** [aminabedi68/Mikhak#5]
سلام
اول از همه یه تشکر ویژه از شما بابت این فونت زیبا و آزاد
یه درخواست داشتم. میشه نسخه‌ی با نقاط جدا واسه حروف دونقطه‌ای و سه‌نقطه‌ای هم داشته باشیم.
من خودم واسه استفاده شخصی خودم کمی با فونت فورج تغییرش دادم و از اون نقطه تکی واسه ساخت دونقطه و سه‌نقطه استفاده کردم. ولی چیزی که واضحه اینه که منی که هیچ تخصصی در این زمینه ندارم نمی‌تونم به خوبی اینا رو از کار در بیارم. ولی خوب شما خودتون تخصصتون همینه و قطعا نتیجه کار شما خیلی خوب خواهد شد.
با سپاس دوباره از شما

**Comment by aminabedi68** [comment]
سلام، خیلی ممنون از توجه شما
پیشنهاد خوبیه 👍 برای تمام نسخه‌ها تو ورژن آینده انجام میشه ایشالا

**Comment by mojtaba82** [comment]
استعداد و میخک واقعا فونت‌های قشنگی هستن.
ممنون از شما که با نشر آزاد این فونت‌ها به زیباسازی وب فارسی کمک کردین

**Comment by aminabedi68** [comment]
بسیار ممنونم، در نسخۀ سوم اضافه شد.

**Comment by mojtaba82** [comment]
بسیار عالی. ممنون از زحمات شما
فونت‌های میخک و استعداد رو خیلی دوست دارم
