### ISSUE TITLE
ی روی ه

### ISSUE THREAD

**Issue by bateni** [aminabedi68/Mikhak#6]
سلام و ممنون بابت طراحی این قلم زیبا.

نشانهٔ ی روی ه در این قلم شبیه به همزه است. آیا عمداً این‌طوری طراحی کردیش؟
بهتر نیست شبیه به سر ی دو تا قوس داشته باشه؟ این طوری هماهنگیش با طبیعت قوسی قلم بیشتر میشه.

**Comment by bateni** [comment]
شاید اشتباه از منه... چون توی صفحات تست این‌جا ی روی ه همون طوری است که من می‌خوام.

**Comment by bateni** [comment]
‫توضیحات بیشتر: من از نرم‌افزار ConTeXt برای حروف‌چینی استفاده می‌کنم که کتاب‌خانه OpenType خودش رو داره.  اونجا توی خروجی ه + ٔ به هٔ تبدیل نشده.  برای همین سعی کردم به جداول OpenType نگاه کنم.  با دانش محدود من، یک دستورالعمل جا افتاده.  برای تبدیل ترکیب U+647 و U+654 به U+6C0 باید یک لیگاتور تعریف بشه.  قلم ساحل رو نگاه کردم و دیدم که اون لیگاتور رو داره.  حدس می‌زنم که کروم و بعضی نرم‌افزارهای دیگه شاید لیگاتورهای رایج رو خودشون اضافه می‌کنند... واسه همین توی صفحهٔ تست مشکلی نیست.  یا شاید نسخهٔ دیگه‌ای اونجا وجود دارد.  من از وزن Medium غیرمتغیر استفاده کردم.

**Comment by aminabedi68** [comment]
سلام. خیلی ممنون برای این ایشو
بله، کاملا درسته. منم تعجب کردم. تو نسخۀ جدید حتما در نظر گرفته میشه

**Comment by aminabedi68** [comment]
در نسخۀ سوم برطرف شد.
