### ISSUE TITLE
Were the variable font masters drawn, or generated algorithmically?

### ISSUE THREAD

**Issue by ctrlcctrlv** [aminabedi68/Mikhak#9]
I'd be interested to know how you automatically interpolated two generated “Expand Stroke” of light and heavy weights given they tend to have different point numbers. Surely you had to manually draw over them, right?

**Comment by aminabedi68** [comment]
Hi @ctrlcctrlv 
yes! as you know Expand Stroke function in fontforge generates different number of points in several width/height values(in both low/high Accuracy Targets, bigger numbers are better for that but decrease the quality of the curves)... and even if it works, the black master has some manual optical modifications(expand radius (in black master) decreased somewhere to control saturation of details)
